### ISSUE TITLE
Double linespaces after method and class

### ISSUE THREAD

**Issue by GaryJones** [zendframework/zend-code#103]
PSR2 checking / fixing with `phpcbf`, flags up that the final method in a generated class has two clear linespaces after it, and that there are two clear linespaces after the class (at the end of the file).

![screenshot 2017-02-24 13 46 24](https://cloud.githubusercontent.com/assets/88371/23305858/a9902e62-fa98-11e6-8ff0-74cf92836ea3.png)

Possibly the first `self::LINE_FEED` [here](https://github.com/zendframework/zend-code/blob/2899c17f83a7207f2d7f53ec2f421204d3beea27/src/Generator/ClassGenerator.php#L1084) is the cause of the linespaces after the final method, and the second in combination with [this one](https://github.com/zendframework/zend-code/blob/2899c17f83a7207f2d7f53ec2f421204d3beea27/src/Generator/FileGenerator.php#L539) gives the double lines at the end of the file?

**Comment by Ocramius** [comment]
That's kinda in the "won't fix" scenario. Zend\Code produces artifacts, not
well-formatted code (that's really secondary)

**Comment by GaryJones** [comment]
Is there a negative to having artefacts that are well-formatted to PSR-2, since most of it already seems to be?

**Comment by Ocramius** [comment]
No, it's just not worth tracking as bug/issue. Alignment problems are a
huge waste of time inside this lib, since it's mostly string concatenation,
and not AST-based code reconstruction.

**Comment by Ocramius** [comment]
If you're want to send a patch, feel free to do it. Meanwhile closing here.
