### ISSUE TITLE
Add support for PHP 7.2's `object` type hint

### ISSUE THREAD

**Issue by Ocramius** [zendframework/zend-code#110]

**Comment by Ocramius** [comment]
If you never contributed and need pointers, check https://github.com/zendframework/zend-code/pull/87 on a previous patch that added PHP 7.1 features (look for the `iterable` hint)

**Comment by shulard** [comment]
Hello !

I'll be glad to take a look 😄.

Is the impact exactly the same than `iterable` hint ? Seems more complicated in the tests than in the code...

**Comment by Ocramius** [comment]
Yes, same impact as `iterable`, and indeed, it's about tests 👍

**Comment by shulard** [comment]
Ok so I'll try to submit a PR before the end of the week 😄.

**Comment by Ocramius** [comment]
Handled in #112
