### ISSUE TITLE
TypeGenerator add a backslash for a custom type with ParameterGenerator

### ISSUE THREAD

**Issue by florentsorel** [zendframework/zend-code#117]
Hello,

I have a problem with `TypeGenerator` when it's used with `ParameterGenerator`.

The output from `generate` method is [return $nullable . '\\' . $this->type;](https://github.com/zendframework/zend-code/blob/master/src/Generator/TypeGenerator.php#L101)

I'm using it like this:

```php
$this->addUse('Zend\EventManager\EventInterface');

$method = new MethodGenerator();
$method->setName('onBootstrap');

$method->setParameter(
    new ParameterGenerator(
        'event',
        'EventInterface'
    )
);

$this->addMethodFromGenerator($method);
```
The issue here is when the file is generated, the parameter type looks like:

```php
use Zend\EventManager\EventInterface;

public function onBootstrap(\EventInterface $event)
{
}
```

Could you provide a way to generate short namespace without backslash for `ParameterGenerator`? (because `$nullable` will always be empty from the `ParameterGenerator` context.)

Like when we define implemented interfaces the method `generateShortOrCompleteClassname` is [called](https://github.com/zendframework/zend-code/blob/master/src/Generator/ClassGenerator.php#L1059)  in [ClassGenerator](https://github.com/zendframework/zend-code/blob/master/src/Generator/ClassGenerator.php#L1128)

If the use statment exists, then use short synthax instead of fully qualified name.

**Comment by Ocramius** [comment]
You have to pass the FQCN, not just the short name.

**Comment by Ocramius** [comment]
See https://github.com/zendframework/zend-code/issues/76

**Comment by Ocramius** [comment]
To clarify further: this was discussed before.

The code generator is a code generator, and changing parameters given based on context is a mess that leads to an infinite amount of bugs down the line.

Make it working code, then focus on optimising imports later (can be done with an AST pass, for example, but not with this library)
