### ISSUE TITLE
ClassScanner produces invalid class name that only contains namespace 

### ISSUE THREAD

**Issue by bashofmann** [zendframework/zend-code#124]
We just discovered some weird case where the ClassScanner produces an invalid class  name that only contains the namespace of the class instead of the full qualified class name.

Version used: 3.2.0

Minimal reproduction code:

```
<?php
namespace foo\bar {

    class SomeClass {

        public function someMethod() {
            $foo = 'foo';
            $label = true ? "test ${foo} test" : "test ${foo}";

            return [
                'label' => $label,
                'class' => self::class
            ];
        }
    }
}

namespace {
    require_once __DIR__ . '/vendor/autoload.php';

    $fileScanner = new \Zend\Code\Scanner\FileScanner(__FILE__);

    foreach ($fileScanner->getClasses() as $class) {
        echo $class->getName() . PHP_EOL;
    }

    print_r($fileScanner->getClassNames());
}
```

Expected output:

```
foo\bar\SomeClass
Array
(
    [0] => foo\bar\SomeClass
)
```

Actual output:

```
foo\bar\
Array
(
    [0] => foo\bar\SomeClass
)
```

The FileScanner actually gets the correct class name.

It works correctly if you either remove the reference to "self::class" or one of the "${foo}" usages.

**Comment by Ocramius** [comment]
Fairly sure that the class scanner can't deal with any PHP 5.4+ feature.
The entire namespace is going to be removed soon though

**Comment by bashofmann** [comment]
Is there going to be a replacement, or do you have a recommendation for something similar? I'd rather not use reflection for our use case.

**Comment by djmattyg007** [comment]
@bashofmann I recommend this: https://github.com/nikic/PHP-Parser it's developed and maintained by one of the core developers of PHP itself.

**Comment by Ocramius** [comment]
See Roave/BetterReflection (https://github.com/Roave/BetterReflection),
which doesn't cause loading of the files you are reflecting.

**Comment by djmattyg007** [comment]
The latter is built on top of the former :)

**Comment by bashofmann** [comment]
Ok thanks for the pointers. Since the feature is going away, I guess we can close this issue then.
