### ISSUE TITLE
ValueGenerator array with FQCN as key with class name resolution

### ISSUE THREAD

**Issue by florentsorel** [zendframework/zend-code#127]
Hi,

Just wondering if it's possible to create an array with ValueGenerator like this:

```php
Test\TestController::class => Test\Controller\TestControllerFactory::class,
```

Currently I have this:
```php
'Test\TestController::class' => Test\Controller\TestControllerFactory::class,
```

I think it's because of that [line](https://github.com/zendframework/zend-code/blob/master/src/Generator/ValueGenerator.php#L422) with [escape method](https://github.com/zendframework/zend-code/blob/master/src/Generator/ValueGenerator.php#L454).

The value is not escaped and the ```::``` constant [exists](https://github.com/zendframework/zend-code/blob/master/src/Generator/ValueGenerator.php#L126).

**Comment by Ocramius** [comment]
@florentsorel keys can only be evaluated constants. `Foo::class` is actually the evaluated constant `Foo` at runtime, but `Foo::class` is just one possible representation.

The feature is overall not available in the `ValueGenerator`, and would need to be added, where a value is to be marked as a class reference.

**Comment by Ocramius** [comment]
Also, IMO, this isn't really needed. What's the use-case for this kind of API?

**Comment by florentsorel** [comment]
In ou ZF3 project we use class name resolution in every configuration file and my project is to build a CLI tool for generating some file for our ZF3 project for productivity.

For example, It's useful when we refactoring some classes because some IDE can't refactor a class if the key is a string.

Currently, if the values can use this feature, the keys should also be able to use it.

**Comment by Ocramius** [comment]
Eh, effectively it's just generating the value: how it is generating it is not that important.

PHPStorm can refactor those keys out of the box, by the way.

**Comment by florentsorel** [comment]
Yes I know for PHPStorm, but Netbeans (for example) can't do that.

So, can you implement that? :)

**Comment by Ocramius** [comment]
It's open source: initiative is on you, as well as feasibility analysis.

**Comment by florentsorel** [comment]
Ok, I will look into this when I'll have some time.

Just to know, currently, why the value can use class name resolution and the key can't?

**Comment by Ocramius** [comment]
@florentsorel I didn't know it could, but keys in arrays are quite restrictive, so it was probably never thought out.

**Comment by florentsorel** [comment]
@Ocramius I have something but it's really ugly but it's work, because as you said, the keys are restrictive.

```php
$outputParts[] = ((is_int($n) || strpos($n, '::') !== false) ? $n : self::escape($n)) . ' => ' . $partV;
```

**Comment by florentsorel** [comment]
There is an issue :/
When I include the file which contains an array, the class name resolution is interpreted by PHP, so every time I write the file, the class name resolution which already exists ```::class``` name resolution becomes a string :(

**Comment by florentsorel** [comment]
With the new updates, it is possible to achieve my request?

**Comment by Ocramius** [comment]
> ```php
 > $outputParts[] = ((is_int($n) || strpos($n, '::') !== false) ? $n : self::escape($n)) . ' => ' . $partV;
 > ```

There is no guarantee from the consumer of the API that `::` isn't an input value: this is not the way to go about determining if a value is "special" or not, and only introduces security issues.

If you need to manipulate how a key is produced, you need a new *type* (not `string`).

Meanwhile, closing here as per https://github.com/zendframework/zend-code/issues/127#issuecomment-319087555

If you have a proposal, send a pull request with the new API (and tests) instead.
