### ISSUE TITLE
3.2.0 Release of Zend-Code introduces Backward Incompatible changes 

### ISSUE THREAD

**Issue by maghamed** [zendframework/zend-code#129]
3.2.0 Release of Zend-Code introduces Backward Incompatible changes and breaks Applications relying on zend-code using minor version.

https://github.com/zendframework/zend-code/releases/tag/release-3.2.0

> #114 Increased
> minimum supported PHP version to ^7.1.0

Magento 2 composer:
https://github.com/magento/magento2/blob/develop/composer.json#L13
`"zendframework/zend-code": "^3.1.0"`

https://getcomposer.org/doc/articles/versions.md#caret-version-range-

>The ^ operator behaves very similarly ... and will always allow non-breaking updates.

**Comment by Ocramius** [comment]
Oh, I see.

This is a misunderstanding: no BC breaks happening.

Please see http://doctrine-project.org/2017/07/25/php-7.1-requirement-and-composer.html

Also https://github.com/doctrine/instantiator/issues/33

ZF also has bumped requirements multiple times, but I don't know where we blogged about it in the past.

**Comment by Ocramius** [comment]
If you can, please transpose this info also on the other issue tracker

**Comment by maghamed** [comment]
@Ocramius  thanks for the update. After discussion in Magento, we've decided to keep the same approach as well.

Will close the current issue.

**Comment by Ocramius** [comment]
@maghamed :+1:
