### ISSUE TITLE
"Nesting level too deep" when comparing ClassGenerator objects

### ISSUE THREAD

**Issue by JuJuDropThor** [zendframework/zend-code#149]
Hi guys

with that :

```
use Zend\Code\Generator\ClassGenerator;
$a = new ClassGenerator();
$b = new ClassGenerator();
var_dump($a == $b);
```

That error occur : Fatal error: Nesting level too deep - recursive dependency?
Some unit tests can't be performed because of that.

**Comment by Ocramius** [comment]
This is normal/not a bug. PHP's `==` is generally unsafe and can only
really be used on objects without internal recursion.
