### ISSUE TITLE
ValueGenerator recursive setIndentation

### ISSUE THREAD

**Issue by hxss** [zendframework/zend-code#163]
On [363 line](https://github.com/zendframework/zend-code/blob/master/src/Generator/ValueGenerator.php#L363) ValueGenerator creates childs but dont pass to them self indentation. So when I create new ValueGenerator and use `setIndentation` method I can set only first level childs indentation.

**Comment by Ocramius** [comment]
Ref:

https://github.com/zendframework/zend-code/blob/4a7f6785ef0567423a4d68d76986673eb297fac4/src/Generator/ValueGenerator.php#L363

**Comment by Ocramius** [comment]
@hxss you mean that multiline-dumped values are not aligned? Doesn't sound like a big deal to me...

**Comment by hxss** [comment]
@Ocramius please see this example:
```
$generator = new Zend\Code\Generator\ValueGenerator([
		'a' => [
			'b' => [
				'c' => 'd',
			]
		],
	]);
	$generator->setIndentation("\t");

	echo $generator->generate();
```
output:
```
array(
	'a' => array(
        'b' => array(
            'c' => 'd',
        ),
    ),
)
```

We have 1 tab before `'a'` and 4 spaces as indentation on other levels of tree.

**Comment by Ocramius** [comment]
Yeah, this is not fixable, unless we touch the `var_export()` output, which we shouldn't do.

This is too much risk (really, it's not that trivial) for a problem in alignment, so I'm going to close it as "won't fix", sorry.

**Comment by hxss** [comment]
after 363 line need to append `$curValue->setIndentation($this->indentation);`
https://github.com/zendframework/zend-code/blob/4a7f6785ef0567423a4d68d76986673eb297fac4/src/Generator/ValueGenerator.php#L363

**Comment by hxss** [comment]
@Ocramius in my test `$curValue->setIndentation($this->indentation);` solve the problem.

**Comment by Ocramius** [comment]
@hxss send a patch then: re-opening (also: didn't know the value generator could already do that, thanks for checking!)

**Comment by Ocramius** [comment]
Please remember to add a test case, if yo do

**Comment by Ocramius** [comment]
Handled in #164
