### ISSUE TITLE
Reflection\MethodReflection::extractMethodContents stumbles over a static keyword

### ISSUE THREAD

**Issue by downace** [zendframework/zend-code#168]
When `static` keyword is present in method body, `extractMethodContents` ignores it and everything after.

Reproducible with zend-code@3.3.1

Reproduction:

```php
class X {
    public function method() {
        var_dump(static::class);
    }
}

$method = new \Zend\Code\Reflection\MethodReflection(X::class, 'method');

(new X)->method();
var_dump($method->getBody());
```

Output:
```
string(1) "X"
string(18) "
        var_dump("
```

`self` works fine, but it is not suitable in some cases.

**Comment by Ocramius** [comment]
Closing due to https://github.com/zendframework/zend-code/issues/91 - we're deprecating all of this stuff, so I strongly endorse moving to https://github.com/Roave/BetterReflection for any method body introspection you may want to perform.
