### ISSUE TITLE
Check Documentation Tables

### ISSUE THREAD

**Issue by GeeH** [zendframework/zend-code#17]
# Check the tables in a document

> TLDR; All tables should be in the format of GHFM using ```|``` and ```-``` as horizontal and vertical separators respectively

Check all tables are in the correct format. Please don't use leading and trailing ```|``` - more information on github flavoured markdown tables can be found [here](https://help.github.com/articles/github-flavored-markdown/#tables).

**Comment by froschdesign** [comment]
No tables included.
