### ISSUE TITLE
Method Zend\Code\Generator\ValueGenerator::__toString() must not throw an exception (with PHP 7.3)

### ISSUE THREAD

**Issue by k00ni** [zendframework/zend-code#178]
The class [ValueGenerator](https://github.com/zendframework/zend-code/blob/master/src/Generator/ValueGenerator.php#L485) may throw an exception inside `__toString` which is [forbidden](https://www.php.net/manual/en/migration52.incompatible.php) (look for `Exceptions can not be thrown from __toString() methods.`) and leads to a fatal error in my case. I am running a Symfony application, which indirectly uses `zend-code`. 

Are you aware of this? I would propose moving the functionality in a separate function or not throw an exception in `__toString` (or referenced functions) at all.

Thank you for the feedback.

**Comment by michalbundyra** [comment]
@k00ni Since PHP 7.4 we can throw exceptions in `__toString()` method - see:
https://www.php.net/manual/en/migration74.new-features.php#migration74.new-features.core.tostring-exceptions

Can you provide more details about your use case when you are getting the exception? Thanks!

**Comment by k00ni** [comment]
Hi @michalbundyra, thank you for the quick reply.

> Since PHP 7.4 we can throw exceptions in __toString() method

Ok, good to know :)

> Can you provide more details about your use case when you are getting the exception?

I am running PHP `7.3`, no xdebug.

My use case involves:
* Symfony 4.4.1
* Doctrine ORM 2.6.6
* PHPUnit 8.x

When running a simple test which requires the `Kernel` and `Doctrine`, i get the following error:

```
Fatal error: Method Zend\Code\Generator\ValueGenerator::__toString() must not throw an 
exception, caught ErrorException: Warning: get_class() expects parameter 1 to be object, 
resource given in 
/var/www/html/vendor/zendframework/zend-code/src/Generator/ParameterGenerator.php on line 0
!!  PHP Fatal error:  Method Zend\Code\Generator\ValueGenerator::__toString() must not 
throw an exception, caught ErrorException: Warning: get_class() expects parameter 1 to 
be object, resource given in 
/var/www/html/vendor/zendframework/zend-code/src/Generator/ParameterGenerator.php on line 0
!!  Symfony\Component\ErrorHandler\Error\FatalError {#1977
!!    -error: array:4 [
!!      "type" => 1
!!      "message" => "Method Zend\Code\Generator\ValueGenerator::__toString() must not
throw an exception, caught ErrorException: Warning: get_class() expects parameter 1 to be 
object, resource given"
!!      "file" => "/var/www/html/vendor/zendframework/zend-code/src/Generator/ParameterGenerator.php"
!!      "line" => 0
!!    ]
!!    #message: "Error: Method Zend\Code\Generator\ValueGenerator::__toString() must 
not throw an exception, caught ErrorException: Warning: get_class() expects parameter 
1 to be object, resource given"
!!    #code: 0
!!    #file: "./vendor/zendframework/zend-code/src/Generator/ParameterGenerator.php"
!!    #line: 0
!!  }
```

I am not familiar with Symfony, Doctrine or Zend internals, therefore can't located the source of the error. I am not even sure, if that is "your" problem, but i thought its a good start to ask the first one in the line.

**Comment by k00ni** [comment]
I moved on to another solution for my problem, which means, i don't get this error anymore. But it maybe still of interest to you. Please close, if not.

**Comment by michalbundyra** [comment]
@k00ni I see the issue - in case value is resource in the exception message we try to get_class of resource, which is not working:

https://github.com/zendframework/zend-code/blob/a277be91693d7f0ef660212839fb5317b1e94314/src/Generator/ValueGenerator.php#L438-L442

Still, seems to be that your code in some place is (was?) invalid.

Would you be able to share your solution which solve your problem, please?

**Comment by k00ni** [comment]
I had problems getting PHPUnit 8.x + Doctrine 2.7 running with Symfony 4.4.1.

After hours of searching it resulted in the following solution: https://github.com/symfony/symfony-docs/issues/12788#issuecomment-563921206 . 

I got the error above when trying to setup Doctrine with a metadata cache. Unfortunately, i can't find my configuration at that time anymore. I am still new to this and its hard to track all these changes and new features/components.

**Comment by k00ni** [comment]
Thank you for the refinements.
