### ISSUE TITLE
Check For Blockquotes In Docs

### ISSUE THREAD

**Issue by GeeH** [zendframework/zend-code#18]
# Check the document for bad blockquoutes

> TLDR; Check blockquotes are formatted correctly using ```>``` and check headings in blockquotes are using ```###```

Blockquotes are donated by a single greater than character and then a space. Make sure all the blockquotes in every doc file are correctly formatted. Headings in blockquotes should use ```###``` and not bold.

Any paragraph spacing in blockquotes should be marked using a single greater than, then a space.

**Comment by froschdesign** [comment]
No notes included.
