### ISSUE TITLE
PHP Fatal error: Class 'Zend\Stdlib\ArrayObject' not found in vendor/zendframework/zend-code/src/Generator/ValueGenerator.php on line 89

### ISSUE THREAD

**Issue by narozhniyy** [zendframework/zend-code#21]
HI,
I have issue with ``` Ocramius/ProxyManager ``` package. This package require to ``` zendframework/zend-code ``` and guys from  Ocramius/ProxyManager asked me to reported about this issue to you.
You can read about issue here [Ocramius/ProxyManager](https://github.com/Ocramius/ProxyManager/issues/260)

Thanks

**Comment by nicolas-grekas** [comment]
See https://github.com/Ocramius/ProxyManager/issues/260#issuecomment-156962918
