### ISSUE TITLE
Can't install with composer

### ISSUE THREAD

**Issue by moon0326** [zendframework/zend-code#27]
Hi,

I'm trying to install this repository using composer.

When I run ```composer require zendframework/zend-code```, I get the following error.

```
  Problem 1
    - zendframework/zend-code 2.6.0 requires zendframework/zend-eventmanager ^2.6|^3.0 -> satisfiable by zendframework/zend-eventmanager[2.6.0].
    - zendframework/zend-code 2.6.1 requires zendframework/zend-eventmanager ^2.6|^3.0 -> satisfiable by zendframework/zend-eventmanager[2.6.0].
    - zendframework/zend-eventmanager 2.6.0 requires athletic/athletic dev-master -> no matching package found.
    - Installation request for zendframework/zend-code ^2.6 -> satisfiable by zendframework/zend-code[2.6.0, 2.6.1].
```

If I try to install ```zendframework/zend-eventmanager``` first, I still get an error.

How do I install zend-code?

**Comment by Ocramius** [comment]
Indeed, the eventmanager 2.6.0 was tagged with athletic in `require` instead of `require-dev`. Fixing that.

**Comment by Ocramius** [comment]
Corrected: https://github.com/zendframework/zend-eventmanager/releases/tag/release-2.6.1

**Comment by Ocramius** [comment]
Ref: zendframework/zend-eventmanager#12

**Comment by moon0326** [comment]
Thank you @Ocramius
