### ISSUE TITLE
[RFC] PHP7 scalar type-hints and return type-hints support

### ISSUE THREAD

**Issue by Ocramius** [zendframework/zend-code#29]
I've been working on this in Ocramius/ProxyManager#241, but then figured out that I really needed to upgrade the core package.

There are some areas of the code that will be affected by BC breaks, and therefore this needs to go in 3.0.0:
 * [this docblock stuff needs to die (causes bugs)](https://github.com/zendframework/zend-code/blob/cd2d697af1fd0182859c14ad93433f737e52d5c5/src/Reflection/ParameterReflection.php#L93-L96)
 * removing PHP5 support (maintaining compatibility with PHP5 is more than problematic, after a first skim of the test suite)

I'm willing to take on this piece of work, and will likely send in an example patch tomorrow.

**Comment by Maks3w** [comment]
About to remove PHP5 support. What things should be removed? IIRC PHP7 scalar typehints are optional

**Comment by Ocramius** [comment]
@Maks3w the problem is that some of the API of zend-code directly clashes with the reflection API: for example `ReflectionParameter#getType()`, which was initially non-inherited, and currently completely obfuscates the API.

There are bigger issues in the component itself (from a design perspective), but keeping 5.5+ compat and also fixing the 7.x compat is not worth it and way too complex. Yes, it could be done, but it would just be a blood bath.

**Comment by weierophinney** [comment]
Closed with #30.
