### ISSUE TITLE
Issue with new lines on windows

### ISSUE THREAD

**Issue by tmilos** [zendframework/zend-code#39]
I'm using PHP on windows but have set IDE intentionally to make unix new lines ``\n``, not windows ones ``\r\n``.
When running ``FileGenerator::fromReflectedFileName()`` on such file, I got exception

```
Undefined offset: 1

D:\www\home\tmilos\model\vendor\zendframework\zend-code\src\Generator\MethodGenerator.php:98
D:\www\home\tmilos\model\vendor\zendframework\zend-code\src\Generator\MethodGenerator.php:77
D:\www\home\tmilos\model\vendor\zendframework\zend-code\src\Generator\ClassGenerator.php:146
D:\www\home\tmilos\model\vendor\zendframework\zend-code\src\Generator\FileGenerator.php:96
D:\www\home\tmilos\model\vendor\zendframework\zend-code\src\Generator\FileGenerator.php:77
```

Tested on zendframework/zend-code v3.0.1

Debuging shows the source of the problem is with inconsistent line endings in the project:

1) During loading ``MethodReflection::extractMethodContents()`` implodes lines with ``\n``

2) While ``MethodGenerator::clearBodyIndention()`` explodes what ``MethodReflection`` did before with ``PHP_EOL``

So, it seems this lib will work only if ``PHP_EOL === "\n"`` and guess that excludes php windows builds.

It would be nice you fix that and use consistent line endings.

**Comment by Toyinster** [comment]
I have the exact same issue.

`$indention = str_replace(trim($lines[1]), '', $lines[1]);`

is causing the Undefined offset: 1

**Comment by 503geek** [comment]
I ran into this issue as well. I haven't done a TON of testing on this yet, so hopefully I won't lead anyone astray but it looks like setting "auto_detect_line_endings = On" in php.ini on a Windows dev box potentially fixes the issue (on my machine using xampp it was commented-out by default). I'm basically two weeks into Symfony development so... YMMV but hopefully this will help someone.
