### ISSUE TITLE
Line ending bug on windows

### ISSUE THREAD

**Issue by mikeSimonson** [zendframework/zend-code#45]
Hi,

I received a bug report on [doctrine/doctrineMigrationsBundle](https://github.com/doctrine/DoctrineMigrationsBundle/issues/154) for an elusive bug that only happen on windows. It looks like this code line is the cause of the issue. https://github.com/zendframework/zend-code/blob/master/src/Generator/MethodGenerator.php#L96

I guess that the assumption is that the first line will always be an empty one (aka only containing a new line). It works perfectly on linux but on windows the explode call might return the whole body of the function as one line. Explode will never find the windows line ending (\r\n) if the code was build on linux.

From that assumption, the issue could be fixed just by replacing the the PHP_EOL param with "\n" but I don't know what kind of side effect the trailling "\r"might cause.

Thanks for your time

**Comment by mikeSimonson** [comment]
Duplicate or linked to #39

**Comment by jckeen** [comment]
So, just for your information, ran into this bug today. Just posting some information for you. 
Started using XAMPP with PHP 7. doctrine/doctrineMigrationsBundle works with my migrations, but it only works before I run a composer update that updates  ocramius/proxy-manager from version 1.0.2 to 2.0.1, and zendframework/zend-code from 2.6.2 to 3.0.1. After the update, migrations no longer work and I get the Undefined offset: 1 error. 

Also interesting that the line in question is the same on version 2.6.2 and 3.0.1. Let me know if you have any questions.  Replacing the PHP_EOL with "\n" allows the migration to work, as you pointed out. 
`$lines = explode(PHP_EOL, $body);`

**Comment by mikeSimonson** [comment]
@jckeen Can you track down the behavior change between zend-code 2.6.2 and 3.0.1 with xdebug ?

**Comment by jckeen** [comment]
So far I've been able to fix it by changing the following line _only _ and leaving the previously mentioned line untouched. 
Zend\Code\Reflection\MethodReflection Line 231
from `$functionLine = implode("\n", $lines);`
to `$functionLine = implode(PHP_EOL, $lines);`
It seems like when it's getting Doctrine\DBAL\Schema\Schema.php it's adding the "\n". Then it's looking for PHP_EOL instead in: (
Zend\Code\Generator\MethodGenerator Line: 96 
`$lines = explode(PHP_EOL, $body);`
By adding the PHP_EOL to line 231, it seems more consistent with what it's trying to do. I'm still trying to figure out exactly WHY this doesn't happen in 2.6.2 when these files are identical. 
Side note: Zend\Code\Reflection\MethodReflection Line 194 is also using the "\n". 

I'm unaware of the long term ramifications. Still playing around with it.

**Comment by jckeen** [comment]
@mikeSimonson Ok, so I tracked down why it used to not happen. When I upgraded to PHP 7, ocramius/proxy-manager, which doctrine/migrations requires, updated from 1.* to 2.*. The fromReflection method that throws the error in zend-code: 
https://github.com/zendframework/zend-code/blob/master/src/Generator/MethodGenerator.php#L96
(which is identical in 2.6.2 and 3.0.1) was overwritten by ocramius\ProxyManager\Generator in 1.*, but in 2.* it calls the parent function from zend-code instead, which causes the error.

**Comment by mikeSimonson** [comment]
@jckeen Thanks

**Comment by 503geek** [comment]
I ran into this issue as well. I haven't done a TON of testing on this yet, so hopefully I won't lead anyone astray but it looks like setting "auto_detect_line_endings = On" in php.ini on a Windows dev box potentially fixes the issue (on my machine using xampp it was commented-out by default). I'm basically two weeks into Symfony development so... YMMV but hopefully this will help someone.

**Comment by mikeSimonson** [comment]
I don't think that we want to tell people to change their config to use
that code.

**Comment by Gemorroj** [comment]
same issue :cry:

**Comment by steve-todorov** [comment]
@503geek your suggestion doesn't seem to be working for me. The only workaround which works is what @mikeSimonson suggested.

**Comment by jaccoTopVintage** [comment]
I ran into this issue as well. The problem is caused by a mismatch between the systems line endings (`PHP_EOL`) and the actual file line ending.

This issue can be easily fixed (bonus: 100% backwards compatibility):

In file: [`https://github.com/zendframework/zend-code/blob/release-3.0.1/src/Generator/MethodGenerator.php`:`96`](https://github.com/zendframework/zend-code/blob/master/src/Generator/MethodGenerator.php#L96)

**current:**
`$lines = explode(PHP_EOL, $body);`

**proposed:**
`$lines = explode("\n", preg_replace('/\r\n?/', "\n", $body));`

*explaination*
The proposed solution replaces any non `LF` line ending (`CR`, `CRLF`), into `LF`.

**Comment by jaccoTopVintage** [comment]
@tiger-seo

Thanks for mentioning my name, it made me re-read my suggestion. 

**My suggested *further improvement* code is wrong**; I should have double checked my "*A further improvement could be*" instead of quickly adding another thought.

It should be (I checked this time):
```
$lines = explode("\n", preg_replace('/\r\n?/', "\n", $body));
if (count($lines) > 0) {
	$indention = str_replace(trim($lines[1]), '', $lines[1]);
} else {
	$indention = '';
}
```

My sincere apologies.
