### ISSUE TITLE
PHP Version required on composer.json does not accept 7.0.5 ?

### ISSUE THREAD

**Issue by ricardofiorani** [zendframework/zend-code#53]
The PHP version that is required on the composer.json accepts PHP 7.0.0 until 7.0.4, ignores PHP 7.0.5 and accepts 7.0.6 and above. PHP 7.0.6 wasn't even released yet.

        "php": "^5.5 || 7.0.0 - 7.0.4 || ^7.0.6",

**Comment by ricardofiorani** [comment]
Nevermind.

**Comment by weierophinney** [comment]
Yes, please see #49 - a bug in PHP 7.0.5's shipped tokenizer means the component cannot work with that version. It's been resolved, and will be released with version 7.0.6.
