### ISSUE TITLE
ClassGenerator::fromReflection() breaks extends and implements

### ISSUE THREAD

**Issue by pburggraf** [zendframework/zend-code#64]
It is not possible to load a class that that extends or implements other classes without breaking the fully qualified names of the classes.

For example, if you load a reflection of this class
```
namespace Sample\ReflectionIssue;

class SampleClass
    extends \Sample\ReflectionIssue\ExtendableClass
    implements \Sample\ReflectionIssue\InterfaceClass
{ ... }
```
via `$foo = ClassGenerator::fromReflection(ClassReflection(new \Sample\ReflectionIssue\SampleClass()));` it will generate the following (invalid) output:
```
namespace Sample\ReflectionIssue;

class SampleClass
    extends Sample\ReflectionIssue\ExtendableClass
    implements Sample\ReflectionIssue\InterfaceClass
{ ... }
```
It's missing the leading backslash in front of the fully qualified class name.

**Comment by veewee** [comment]
I've bumped into the same issue on PHP 7.0.1 (cli).
On top of this I noticed while using the `FileGenerator::fromReflectedFileName()` method, that it also changes Interface names that are included with a use statement into the FQN.

For example:

Source
```php
<?php

namespace Testing;

use Phpro\SoapClient\Type\ResultInterface;

class ArrayOfForecast implements ResultInterface
{
// OLD BODY
}
```

Destination:
```php
<?php

namespace Testing;

use Phpro\SoapClient\Type\ResultInterface;

class ArrayOfForecast implements Phpro\SoapClient\Type\ResultInterface
{
// NEW BODY
}
```

As you can see the trailing slash is missing and it should rather use the short name of the interface like in the source file.
