### ISSUE TITLE
Version 3.0.3 breaks Symfony PHP Dependency Injection

### ISSUE THREAD

**Issue by entepe85** [zendframework/zend-code#74]
After updating zend-code to version 3.0.3 through `composer update` the following error is thrown upon clearing the Symfony cache:

`Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Parse error: syntax error, unexpected '\' (T_NS_SEPARATOR), expecting identifier (T_STRING) in [...]var/cache/dev/appDevDebugProjectContainer.php:7161`

Here's the corresponding line of code:
`class VichUploaderBundleHandlerUploadHandler_000000003557d388000000006581de10da75941a549785cf26d7df71050c90e4 extends \\Vich\UploaderBundle\Handler\UploadHandler implements \\ProxyManager\Proxy\VirtualProxyInterface {`

Reverting zend-code back to 3.0.2 through composer.json fixes the above issue.

**Comment by entepe85** [comment]
See [#19201](https://github.com/symfony/symfony/issues/19201).

**Comment by qRoC** [comment]
https://github.com/qRoC/zend-code/commit/4920b011500ca28c7cb2199d2b96bf2cf06fea28

**Comment by Najki** [comment]
You can try this in your composer.json while waiting for the fix to be released (hopefully in 3.0.4)
`"zendframework/zend-code": "~3.0.2, !=3.0.3"`

**Comment by kdambekalns** [comment]
also see https://github.com/Ocramius/ProxyManager/issues/321

**Comment by Ocramius** [comment]
Thanks @weierophinney, @qRoC and @entepe85!
