### ISSUE TITLE
ClassReflection::getTraits() behaves inconsistently

### ISSUE THREAD

**Issue by GeeH** [zendframework/zend-code#77]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

___
Original Issue: https://api.github.com/repos/zendframework/zendframework/issues/7428
User: @stepashka69
Created On: 2015-04-07T13:11:58Z
Updated At: 2015-11-06T21:16:27Z
Body
Hello,

The problem is that sometimes the function returns *array* and sometimes (when there are not traits) *null*.
It would be also nice to have a phpdoc for the function.

The problem was caught on the following code:
```
// $class is an instance of ClassReflection
foreach ($class->getTraits() as $trait) {
//...
}
```

The code gives PHP error "Invalid argument supplied for foreach()" when there are no traits in the class. 

The problem is in file ClassReflection.php line 185 . It returns null but it will be more logical to return $vals (empty array at that stage). 

```
    public function getTraits()
    {
        $vals = array();
        $traits = parent::getTraits();
        if (! $traits) {
            return; // It would be better to return $vals here
        }

        foreach ($traits as $trait) {
            $vals[] = new ClassReflection($trait->getName());
        }

        return $vals;
    }
```

___
### Comment
User: @samsonasik
Created On: 2015-04-07T15:41:42Z
Updated At: 2015-04-07T15:41:42Z
Body
linked with #7431 

___

**Comment by samsonasik** [comment]
already fixed by https://github.com/zendframework/zendframework/pull/7431 , close-able.
