### ISSUE TITLE
Unindentified index 1

### ISSUE THREAD

**Issue by Chris-Kruining** [zendframework/zend-code#82]
src/Generator/MethodGenerator.php -> clearBodyIndention (lines 90 to 109)

is trying to parse the following body: 

array (size=1)
  0 => string '              return $this->getServiceLocator()->get('Core\Page\Service\PageService');' (length=86)

(this is a vardump of the result from the explode on line 96)

this method asumes that all my functions have an enter at the first line, I'd suggest to make this method a tad bit smarter so that it is able to work when you have a oneliner, like I have in my case.

[zendframework-zend-code-001.txt](https://github.com/zendframework/zend-code/files/365615/zendframework-zend-code-001.txt)

**Comment by Chris-Kruining** [comment]
[zendframework-zend-code-001.txt](https://github.com/zendframework/zend-code/files/365623/zendframework-zend-code-001.txt)

oops, still getting used to php7 :P

**Comment by Ocramius** [comment]
Requires a failing test case

**Comment by Chris-Kruining** [comment]
Sorry. I'm new to the 'official' bug reporting. How does such a failing test case look like? Do I make a unit test that fails? Do I suply an exsisting unit test with my function so that that test fails?

**Comment by Ocramius** [comment]
Have a look at the tests in https://github.com/zendframework/zend-code/blob/e21f53c1f8a40dd41245eed1f9887f61a675517b/test/Generator/MethodGeneratorTest.php

**Comment by Chris-Kruining** [comment]
This is the code wich caused the bug; because all the functions are 1-liners the explode on \n will fail to produce an array with more than one result
[zendframework-zend-code-002.txt](https://github.com/zendframework/zend-code/files/368654/zendframework-zend-code-002.txt)

I hope this will help :D

**Comment by Ocramius** [comment]
@Chris-Kruining could you try sending a patch for the `MethodGeneratorTest.php` that I linked above?

**Comment by Chris-Kruining** [comment]
[testClearBodyIndentation.txt](https://github.com/zendframework/zend-code/files/368915/testClearBodyIndentation.txt)

like this? (I couldn't manage to make a pull request, git was being an asshole)

**Comment by Saeven** [comment]
Test checked in
https://github.com/zendframework/zend-code/pull/83

**Comment by Ocramius** [comment]
@Saeven thanks! Closing this one as duplicate.
