### ISSUE TITLE
Support PHP 7.1 `void` return type

### ISSUE THREAD

**Issue by Ocramius** [zendframework/zend-code#84]
As per PHP 7.1, a new `void` return type is introduced ( https://wiki.php.net/rfc/void_return_type )

This basically means that the [`TypeGenerator`](https://github.com/zendframework/zend-code/blob/e21f53c1f8a40dd41245eed1f9887f61a675517b/src/Generator/TypeGenerator.php) needs to be patched to support `void`.

No further changes really needed in this component, as it doesn't really focus on method body generation.

**Comment by webimpress** [comment]
Done in #87 and released with 3.1.0.
