### ISSUE TITLE
PHP Notice in some situation w/o detailed information - zend-code 3.0.4

### ISSUE THREAD

**Issue by aight8** [zendframework/zend-code#93]
```
Notice: Undefined offset: 915 in /var/www/xxx/current/vendor/zendframework/zend-code/src/Scanner/ClassScanner.php on line 943
```

**Comment by Ocramius** [comment]
Can't do anything about this without a trace or more detailed information. Please open a new issue once you have that.

**Comment by aight8** [comment]
Do you know if there is a similar and more stable "ClassScanner" component out there?

**Comment by Ocramius** [comment]
See https://github.com/zendframework/zend-code/issues/91
