### ISSUE TITLE
Fatal error: in C:\xampp\htdocs\magento\magento2\vendor\zendframework\zend-stdlib\src\ArrayObject.php on line 22

### ISSUE THREAD

**Issue by pinkuk** [zendframework/zend-code#98]
After success installation message, while launching admin/frontend getting this error

**Comment by adamlundrigan** [comment]
From the error message posted you are using Magento2.  Please refer to their community for assistance with installation problems.

If you feel this is a bug in the Zend Framework Stdlib component please feel free to re-open with a more complete stack trace ([ArrayObject line 22](https://github.com/zendframework/zend-stdlib/blob/release-2.4.10/src/ArrayObject.php#L22) is just the class line, which gives us no indication of the actual problem)
